config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # www.kitt.com/about

  # defines the naked url root i.e. www.kitt.com
  root to: 'pages#home'
  # get '/', to: 'pages#home'

  # verb 'path', to: 'contoller_name#method'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact', as: 'email'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @members = ['arthur', 'alex', 'celine', 'kat', 'lucien']
  end

  def home
  end

  def contact
    @members = ['arthur', 'alex', 'celine', 'kat', 'lucien']
    if params[:member].present?
      @member = @members.find { |member| member.start_with?(params[:member]) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if action_name != 'home' %>
      <div class="navbar">
        <%= link_to "home", root_path %>
      </div>
    <% end %>
    <%= yield %>
    <div class="footer"></div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Here is some about info</h1>

<ul>
  <% @members.each do |member| %>
    <li><%= member %></li>
  <% end %>
</ul>

<!-- invisible er + tab -->
<!-- visible pe + tab -->

app/views/pages/contact.html.erb
<h2>Get in touch at hello@lewagon.com</h2>

<h2>Who would you like to get in touch with?</h2>

<% if @member %>
  <h3>Here is the info for <%= @member %></h3>
<% end %>


<form action="/contact" method="get">
  <input type="text" name="member" value="<%= params[:member] %>" placeholder="Who are you looking for?">
  <input type="submit">
</form>

app/views/pages/home.html.erb
<h1>Welcome to fake kitt</h1>
<p>Now is <%= Time.now %><p>
<!-- <a href="/about">Go to about</a> -->

<!-- generate a link_to helper lt + tab -->

<%= link_to "See about page", about_path %>
<%= link_to "Get in contact", email_path  %>

<%= link_to about_path do %>
  <h1>GO TO ABOUT</h1>
<% end %>